<nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a span style="color:grey" class="navbar-brand" href="/">Ya Mon Catering</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
            <li <?php if($this->sPage == "about.phtml") echo ' class="active" ' ?>><a span style="color:grey" href="/about">About</a></li>
            <li><a span style="color:grey" href="http://yamoncatering.blogspot.ca/">Blog</a></li>
            <li <?php if($this->sPage == "contact.phtml") echo ' class="active" ' ?>><a span style="color:grey" href="/contact">Contact</a></li>
            <li <?php if($this->sPage == "") echo ' class="active" ' ?>><a span style="color:grey" href="/login">Login</a</li>
            <li <?php if($this->sPage == "crud.phtml") echo ' class="active" ' ?>><a span style="color:grey" href="/crud">Edit</a></li>
        </ul>
    </div><!--/.nav-collapse -->
</nav>
