<?php 
$this->data["title"]="Ya Mon Catering: contact";
$this->layout("_layout.phtml");
?>
<h1>Contact</h1>
<div class="row contact">
    <div class="col-md-8">
        <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false"></script>
        <div style="overflow:hidden;height:500px;width:100%;">
            <div id="gmap_canvas" style="height:500px;width:100%;"></div>
            <style>
                #gmap_canvas img {
                    max-width: none!important;
                    background: none!important
                }
            </style><a class="google-map-code" href="http://www.trivoo.net/gutscheine/schwab/" id="get-map-data">www.trivoo.net</a>
        </div>
        <script type="text/javascript">
            var nLat =43.464399,nLong = -80.521314;
            function init_map() {
                var myOptions = {
                    scrollwheel: false,
                    zoom: 12,
                    center: new google.maps.LatLng(nLat, nLong),
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);
                marker = new google.maps.Marker({
                    map: map,
                    position: new google.maps.LatLng(nLat, nLong)
                });
                infowindow = new google.maps.InfoWindow({
                    content: "<b>Ya Mon Catering</b><br/>Serving from the Tri-City<br/>and the Greater Toronto area"
                });
                google.maps.event.addListener(marker, "click", function () {
                    infowindow.open(map, marker);
                });
                infowindow.open(map, marker);
            }
            google.maps.event.addDomListener(window, 'load', init_map);
        </script>
    </div>
    <div class="col-md-4">
        <?php
        \RHildred\Editable\Markdown::render( __DIR__ . "/contact.md");
        ?>
        <form action="https://rich-hildred.rhcloud.com/Mailer/d1e053066547e27f690ec5190">
            <input type="email" name="email" placeholder="Reply email address" />
            <br />
            <input type="text" name="subject" placeholder="Subject of your inquiry" />
            <br />
            <textarea name="message" placeholder="Your Inquiry"></textarea>
            <br />
            <button type="submit" class="btn btn-primary btn-md">Send</button>
            <button type="reset" class="btn btn-primary btn-md">Reset</button>
            <br />
        </form>

    </div>
</div>
