<?php
$this->data["title"]="Ya Mon Catering: Home";
$this->layout("_layout.phtml");
?>


<img class="glow" id="homelogo" src='/images/LOGO V3.png' alt="ENTER" style="width:50%;height:50%;" usemap="enter">
<map id="click" name="enter">
    <area  shape="circle" coords="400,383,  230" href="/products/1" alt="ENTER" title="site entrance">
</map>

<div >
<audio controls autoplay>
  <source src="/audio/Jamming - instrumental.mp3" type="audio/mpeg">
</audio>
</div>

